config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: %i[show index create new] do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, presence: true, inclusion: { in: %w[chinese japanese italian french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating,
    presence: true,
    numericality: { only_integer: true },
    inclusion: { in: (0..5) }
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "IsItLitt", restaurants_path, class: "navbar-brand" %>
    <%= link_to "+ New restaurant", new_restaurant_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</nav>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1 class="text-center mt-4">Beautiful Restaurants</h1>
<div class="row">
  <% @restaurants.each do |restaurant| %>
    <div class="col-sm-4 d-flex justify-content-center">
    <div class="card text-center mt-5 shadow-sm" style="width: 27rem;">
    <img src="https://picsum.photos/200" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title"><%= restaurant.name %></h5>
        <p class="card-text"><%= restaurant.address %></p>
        <%= link_to "More details", restaurant_path(restaurant), class:"btn btn-info" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<%= simple_form_for (@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>
<p><%= @restaurant.category %></p>
<p><%= link_to "Write a review", new_restaurant_review_path(@restaurant) %></p>
<h3>Reviews</h3>
  <% @restaurant.reviews.each do |review| %>
    <p><%= review.rating %></p>
    <p><%= review.content %></p>
  <% end %>
<p><%= link_to "Back to restaurants", restaurants_path %></p>

app/views/reviews/new.html.erb
<h1>Write a review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>
<%= link_to "Back to #{@restaurant.name}", restaurant_path(@restaurant) %>